version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify the Node.js version compatible with your project
  pre_build:
    commands:
      - echo Pre-build phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build # Compiles the NestJS application
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
